# Generated by Django 5.1.5 on 2025-01-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItem',
        ),
    ]
